export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE';
