export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE';
export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
